# config.yml

#systemd run interval
systemd_timer: '6h'
#if running in docker then we need the container name
cs_container: 'crowdsec' 
#put that key here
bouncerkey: 'crowdsec bouncer key'
#decision duration recommended 72h
ban_duration: '72h'
#custom blocklist 
#save blocklist in your cs-blockdewd directory and replace <0> with the file name
myblocklist: 'blocklist.txt'
#geoip-shell mode if set wrong script will fail
#valid inputs
# 'whitelist'
# 'blacklist'
geoip_mode: 'whitelist'
#Lists need no filtering or only '#' needs filtered
#This is what I use (can be customized)
#These lists will add approx 125k decisions with geoip-shell in use(without this is approx 340k)
urls_standard:
  -  https://raw.githubusercontent.com/borestad/iplists/refs/heads/main/spamhaus/spamhaus-drop.ipv4
  -  https://raw.githubusercontent.com/borestad/iplists/refs/heads/main/spamhaus/spamhaus-asndrop.ipv4
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/et_block.netset
  -  https://raw.githubusercontent.com/stamparm/ipsum/refs/heads/master/levels/2.txt
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_abusers_1d.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level1.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level2.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level3.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/firehol_level4.netset
  -  https://raw.githubusercontent.com/borestad/firehol-mirror/refs/heads/main/ciarmy.ipset
  -  https://raw.githubusercontent.com/ShadowWhisperer/IPs/refs/heads/master/Lists/Threats_Unclassified
  -  https://raw.githubusercontent.com/ShadowWhisperer/IPs/refs/heads/master/Lists/Threats
  -  https://raw.githubusercontent.com/elliotwutingfeng/ThreatFox-IOC-IPs/refs/heads/main/ips.txt
  -  https://binarydefense.com/banlist.txt
  -  https://opendbl.net/lists/bruteforce.list
  -  https://opendbl.net/lists/etknown.list
  -  https://rules.emergingthreats.net/blockrules/compromised-ips.txt
  -  https://raw.githubusercontent.com/Naunter/BT_BlockLists/refs/heads/master/list_1.ThreatFox
  -  https://raw.githubusercontent.com/dewdmadbro/cs-blockdewd/refs/heads/main/blockdewd.sh
