# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run inline bash
        shell: bash
        run: |
          # ── Config
          FILE="dewd-iplist.txt"
          COMMIT_MSG="Update dewd-iplist.txt"
          
          URL1_LIST=(
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/exim-bf.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-bad-user-agent.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-dos-bypass-cache.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-dos-invalid-http-versions.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-dos-random-uri.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-dos-swithcing-ua.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/http-generic-bf.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/iptables-scan-multi_ports.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/mysql-bf.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/nginx-req-limit-exceeded.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/openappsec-request-rate-limit.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/smb-bf.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/ssh-bf.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/tcpudp-flood-traefik.json.txt"
             "https://raw.githubusercontent.com/Y3ll0w/CrowdSec-CAPI-Decisions/main/telnet-bf.json.txt"
          )
          
          URL2_LIST=(
             "https://raw.githubusercontent.com/borestad/blocklist-abuseipdb/refs/heads/main/stats/hallofshame/subnets/abuseipdb-s99-hallofshame-all-75percent.ipv4"
             "https://raw.githubusercontent.com/borestad/blocklist-abuseipdb/refs/heads/main/abuseipdb-s100-3d.ipv4"
          )
        
          # ── Fetch
          fetch1() {
              local url=$1
              info "-----> Fetching  "
              curl -s "$url" | grep -v '^#' >> "$FILE"
          }
          
          fetch2() {
              local url=$1
              info "-----> Fetching"
              curl -s "$url" | grep "# " | grep -v '^#' | awk '{print $1}' >> "$FILE"
          }
          
          info "-----> Fetching lists"
          for url in "${URL1_LIST[@]}"; do 
              fetch1 "$url" 
          done
          
          for url in "${URL2_LIST[@]}"; do 
              fetch2 "$url" 
          done
          
